services:
  - type: web
    name: cold-email-soumya
    runtime: node
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node mailer.js & python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 600
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: API_KEY
        sync: false
      - key: DAILY_LIMIT
        value: "62"
      - key: MORNING_BATCH_SIZE
        value: "30"
      - key: EVENING_BATCH_SIZE
        value: "32"
      - key: MIN_DELAY
        value: "90"
      - key: MAX_DELAY
        value: "240"
